package tictactoe;
/*
 * This source file was generated by the Gradle 'init' task
 */

//import java.util.Random;
import java.util.Scanner;

public class TicTacToe {

    public static void main(String[] args) {

    }
}